"""create_initial_tables

Revision ID: cb51d747f5f3
Revises:
Create Date: 2025-06-21 00:35:26.711950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb51d747f5f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('subcategory_name', sa.String(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('discontinuation_date', sa.Date(), nullable=True),
    sa.Column('price_retail_srp', sa.DECIMAL(), nullable=True),
    sa.Column('price_wholesale', sa.DECIMAL(), nullable=True),
    sa.Column('unit_cost', sa.DECIMAL(), nullable=True),
    sa.Column('package_size', sa.String(), nullable=True),
    sa.Column('product_tier', sa.String(), nullable=True),
    sa.Column('key_features_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_index(op.f('ix_products_category_name'), 'products', ['category_name'], unique=False)
    op.create_index(op.f('ix_products_product_tier'), 'products', ['product_tier'], unique=False)
    op.create_index(op.f('ix_products_sku_id'), 'products', ['sku_id'], unique=True)
    op.create_table('retailers',
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('retailer_name', sa.String(), nullable=False),
    sa.Column('number_of_stores', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('retailer_id')
    )
    op.create_index(op.f('ix_retailers_retailer_id'), 'retailers', ['retailer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retailers_retailer_id'), table_name='retailers')
    op.drop_table('retailers')
    op.drop_index(op.f('ix_products_sku_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_tier'), table_name='products')
    op.drop_index(op.f('ix_products_category_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
